### ISSUE TITLE
yaz-iconv MARC-8 to UTF-8 results in incorrect Record Length

### ISSUE THREAD

**Issue by cajunjoel** [indexdata/yaz#12]
I've been able to reproduce this reliably on a handful of records.

When the record contains MARC-8 encoded special diacritics, such as accented characters, the conversion to UTF-8 works correctly, but the record length indicator (bytes 00-04 of the Leader) of the UTF-8 marc file is incorrect. See the attached ZIP file containing a before and after example. I can provide more if necessary. 

I'm on OS X and yaz (version 1.15.1) was compiled with homebrew. The command I used was: 

`$ yaz-iconv -v -f marc8 -t utf-8 bibno-15.mrc > bibno-15-utf8.mrc`

The results are:

`$ ls -al *bibno-15*`
`-rw-r--r--  1 joelrichard  staff  1318 Apr 26 14:00 bibno-15-utf8.mrc`
`-rw-r--r--  1 joelrichard  staff  1313 Apr 26 14:00 bibno-15.mrc`

The record length in both files is reported as 1313 bytes. I think it should be 1318 for the utf-8 version.

I've scanned the code and I think that the fix may lie somewhere in src/siconv.c in the yaz_iconv() function on line 146. But don't quote me on that. :) 

[MARC8-to-UTF8-Example.zip](https://github.com/indexdata/yaz/files/237291/MARC8-to-UTF8-Example.zip)

**Comment by adamdickmeiss** [comment]
yaz-iconv converts a sequence of bytes and have no understanding of MARC format at all. Instead, use yaz-marcdump which understands MARC structure:
```
yaz-marcdump -f marc8 -t utf8 -o marc bibno-15.mrc >bibno-15-utf8.mrc
```
