### ISSUE TITLE
Checking on 5.34.1 tarball modification/re-upload

### ISSUE THREAD

**Issue by cho-m** [indexdata/yaz#120]
It looks like the tarball (https://download.indexdata.com/pub/yaz/yaz-5.34.1.tar.gz) changed since the original upload and I wanted to confirm this was a valid/intended modification.

Mainly want to check for security reasons prior to rebuilding Homebrew package (https://github.com/Homebrew/homebrew-core/pull/182130)

On Homebrew side, we used the tarball available on 2024-06-20 (https://github.com/Homebrew/homebrew-core/pull/175236) which had a SHA256 of `c7fd8e0222b3b0d1115ad8e7a2ee67be7a2807624d61d5b71854bf5e167ab7a9`. This appears to be the same tarball used by Debian[^1] and Fedora[^2].

https://download.indexdata.com/pub/yaz/ shows the current tarball was uploaded on 2024-06-22 with a sha256 of `393ff4fbbf9194465996236f39efb2962848820247296aec2a6170b0d5d2a44c`.

[^1]: http://deb.debian.org/debian/pool/main/y/yaz/yaz_5.34.1.orig.tar.gz
[^2]: https://src.fedoraproject.org/repo/pkgs/yaz/yaz-5.34.1.tar.gz/sha512/ecb6500598320a7e5db6dc0ede000663991f8b11c3ab2688a8a16e2b14455a0266a4e076ad7b1801201f4a3feab0267b88003b440e4b6d821afa01d561a82d64/yaz-5.34.1.tar.gz

**Comment by jakub-id** [comment]
@cho-m we will take a look at this, I think it's likely that the tarball was modified and re-uploaded. cc @funkymalc

**Comment by jakub-id** [comment]
@cho-m yaz-5.34.2 is now available. We will take care not to update the tarball in case the docs are updated.

**Comment by cho-m** [comment]
Thanks for the confirmation and release notification. I will update to next version in https://github.com/Homebrew/homebrew-core/pull/191394
