### ISSUE TITLE
yaz_xml_get_prop(), xml_get.c

### ISSUE THREAD

**Issue by textbrowser** [indexdata/yaz#26]
The variable argument list ap is not closed properly.

```
va_end(ap); // Please add.
return (const char *) attr->name;
```
```
va_end(ap); // Please add.
return (const char *) attr->children->content;
```

**Comment by MikeTaylor** [comment]
Thanks for spotting all these -- it's good to get some code review.

We'd find it more convenient if you could wrap them all up in a single pull-request, though.

**Comment by adamdickmeiss** [comment]
I think we manage. Thanks.
