### ISSUE TITLE
ZOOM_connection_do_io(), zoom-c.c

### ISSUE THREAD

**Issue by textbrowser** [indexdata/yaz#27]
```int ret = ret = cs_rcvconnect(c->cs);``` should probably be ```int ret = cs_rcvconnect(c->cs);```.

**Comment by MikeTaylor** [comment]
Thanks, well spotted! Now fixed at https://github.com/indexdata/yaz/commit/93b9f0bbae68c78431de37f6be7f42a5171ca7a8
