### ISSUE TITLE
Please use pkg-config to detect icu

### ISSUE THREAD

**Issue by hughmcmaster** [indexdata/yaz#41]
`icu-config` has been deprecated by its upstream developers for some years now. In icu 63.1, `icu-config` is optional to install, but installed by default. In the next version, `icu-config` will no longer be installed by default.

The developers recommend downstream packages use `pkg-config` to detect the icu libraries. I took a quick look at the icu detection definition in yaz's `m4` directory and almost all of that code is redundant.

Please let me know if you need any help with this change.

**Comment by adamdickmeiss** [comment]
Thanks for the report. I think it's clear what needs to be done.

**Comment by hughmcmaster** [comment]
No problem. Feel free to ask if you need any help with this work.
