### ISSUE TITLE
Please include submodule files in the release tarballs

### ISSUE THREAD

**Issue by hughmcmaster** [indexdata/yaz#44]
The release tarballs on GitHub do not include the files from the submodules (e.g. from the m4 directory), making building from source impossible.

Please include these files or convert the submodules to standard directories.

Thank you

**Comment by adamdickmeiss** [comment]
OK.. On GitHub the tag has been used. For tar's with made with 'make dist' , we have always had, http://ftp.indexdata.dk/pub/yaz
