### ISSUE TITLE
Connection does not fail if sru is specified

### ISSUE THREAD

**Issue by mjsir911** [indexdata/yaz#46]
Without any server running on localhost...

Minimum viable example:
```
#include <stdio.h>
#include <yaz/zoom.h>

int main() {
	ZOOM_options opt = ZOOM_options_create();
	// ZOOM_options_set(a, "sru", "soap"); // uncomment for no error
	ZOOM_connection conn = ZOOM_connection_create(opt);
	ZOOM_connection_connect(conn, "localhost", 1234);

	printf("%i\n", ZOOM_connection_errcode(conn));
  
}
```

when the second line of main is uncommented, the connection has no error reported.

**Comment by adamdickmeiss** [comment]
YAZ does not in all cases report an error until you actually send data to the server.. Eg send a search for similar. We won't fix this.

**Comment by MikeTaylor** [comment]
Your expectation is reasonable, but not really implementable in light of the very different way the two underlying protocols work. In Z39.50, Init is an API, with a response, and so `ZOOM_connection_connect` invokes that and reports on the outcome. But in SRU and SRW, there is no Init API — initialization in the ZOOM library is merely preparing an in-memory object's state so it's ready to be used. Nothing actually goes on the wire until you run a search, and _that_ is when an error becomes apparent if there is no server in place.

I don't think there's any way it could be different, short of ZOOM making up its own dummy search and sending that — which would of course make every single ZOOM-over-SRU/SRW program significantly slower, as well as wasting the resources of servers.

**Comment by mjsir911** [comment]
But `ZOOM_connection_connect` does fail on connect! It only stops failing when I set `sru` to `soap` with `ZOOM_options_set(opt, "sru", "soap");`, which is documented as the default value.

The logic behind this can be found here:
https://github.com/indexdata/yaz/blob/ebb947c6c975bb0974ca8e753db1000437d1db01/src/zoom-c.c#L423-L427

which is adding an `http://` prefix if *any* option is given to `sru`, and the `http://` prefix causes the failing to be delayed until a search. If the `http://` prefix is omitted, everything works as expected
