### ISSUE TITLE
Undefined behaviour in call to yaz_diag_to_str()

### ISSUE THREAD

**Issue by hughmcmaster** [indexdata/yaz#54]
```
cqlstrer.c: In function ‘cql_strerror’:
cqlstrer.c:18:12: warning: implicit declaration of function ‘yaz_diag_to_str’; did you mean ‘yaz_diag_srw_str’? [-Wimplicit-function-declaration]
   18 |     return yaz_diag_to_str(code);
      |            ^~~~~~~~~~~~~~~
      |            yaz_diag_srw_str
cqlstrer.c:18:12: warning: returning ‘int’ from a function with return type ‘const char *’ makes pointer from integer without a cast [-Wint-conversion]
   18 |     return yaz_diag_to_str(code);
      |            ^~~~~~~~~~~~~~~~~~~~~
```

`yaz_diag_to_str()` is not called correctly in cqlstrer.c, as it is only passing one variable. The pointer to a struct is missing and should be the first of two arguments.

In addition, the function is implicitly defined, as the function declaration of  `yaz_diag_to_str` is in src/diag-entry.h.

Can you please look into this?

**Comment by adamdickmeiss** [comment]
Fixed in master and will be part of YAZ 5.30.1. Thanks for reporting!
