### ISSUE TITLE
Please include m4 files in your github release tarballs

### ISSUE THREAD

**Issue by hughmcmaster** [indexdata/yaz#56]
Your github release tarballs currently do not compile because the m4 macros are not packaged.

Can you please generate a full tarball, so github releases can be compiled and used?

Thank you

**Comment by adamdickmeiss** [comment]
I don't think I can control how GitHub makes tar balls. We provide these.. which are the result of make dist:
http://ftp.indexdata.dk/pub/yaz/

**Comment by adamdickmeiss** [comment]
Closing this as I don't know a solution to this. Updated the README to clarify.
