### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by mansakondo** [indexdata/yaz#60]
On Ubuntu, after all the installation steps, I got this error:
`error while loading shared libraries`

I had to run this command, in order to create the necessary links for shared libraries:
`sudo ldconfig`

So I think that this should be mention in the doc.

**Comment by dltj** [comment]
Thank you for the comment.  The documentation indirectly covers this need.  In reference to the `make install` command, it says:

> You probably need to have root access in order to perform this.

**Comment by mansakondo** [comment]
Thank you for replying. I haven't mentioned it, but I've ran `make install` with root access, and still got this error when trying to use any library.

I've reproduce the steps multiple times in Docker containers, and the `sudo ldconfig` command is only final step that makes the installation work for me on Ubuntu 20.04.
