### ISSUE TITLE
A ZOOM_connection_destroy() question.

### ISSUE THREAD

**Issue by textbrowser** [indexdata/yaz#62]
Hello.

Could you please open the Discussions for this project? It will allow people to ask questions instead of perhaps bothering you with tickets. :)

I have a question regarding ZOOM_connection_destroy(). Can a connection using the async option be destroyed while the connection is not idle? For example:

- create connection
- set async option
- while(...)
- if interrupted by person, exit while
- ZOOM_connection_destroy(connection) // data may be in transit

Thanks!

**Comment by wafschneider** [comment]
There is an email address provided for support, as well as a fairly low-traffic mailing list -- please see the project [README](https://github.com/indexdata/yaz#mailing-list).

**Comment by textbrowser** [comment]
Thanks. :)
