### ISSUE TITLE
yaz-client vs. zoom API

### ISSUE THREAD

**Issue by andrisi** [indexdata/yaz#63]
I'm using the ZOOM api (through a nodejs wrapper, https://github.com/dengelke/node-zoom2/) and stuck with a strange issue. When running a simple query in yaz-client, it works fine, but if it is ran throught ZOOM API calls, it fails to give any results, which makes me beleive that somehow the same query is sent in different ways, or some option is set silently. Please have a look at: https://github.com/dengelke/node-zoom2/issues/20 which goes as far as discovering that one uses send_Z3950_searchRequest() and the other uses ZOOM_query_prefix().

**Comment by MikeTaylor** [comment]
Andris,

If I were debugging this, I would start by running the same query using the
ZOOM command-line client `zoomsh`. If that works, then you know the problem
is in the ZOOM-based app that you're writing (or maybe the Node wrapper,
which we're not familiar with). If if does NOT work using `zoomsh`, then
you can run it using the `-a -` command-line option -- see
https://software.indexdata.com/yaz/doc/zoomsh.html -- to discover exactly
what requests are being sent.

Good luck.

-- Mike.

**Comment by andrisi** [comment]
Thanks! It does work in zoomsh indeed. I'll close this ticket when I find out the cause.

**Comment by andrisi** [comment]
Thanks for the suggestion @MikeTaylor the problem was in the node wrapper - it is fixed now.

**Comment by MikeTaylor** [comment]
Good to know!
