### ISSUE TITLE
how to set the charset ? In nodejs,  chinese characters are garbled in results whitch returned from some GB2312 servers

### ISSUE THREAD

**Issue by DitieNoder** [indexdata/yaz#64]
I come from here , https://github.com/dengelke/node-zoom2/issues/30 ,please look at this .
In nodejs , I use a module  node-zoom2  whitch compiled from yaz and C .
Because Nodejs only support  one of utf8, ucs2, ascii, binary, base64, hex   ,  so when the result from server is decoded by GB2312 , the Nodejs progame would explain the results by utf8 immediatly ,therefore the chinese characters go garbled .

1、Could you please support to set the charset when sendding request ?  or when  the server return results by GB2312-decode,  the C progame could  encode the results  with  iso-8859-1（or other method ）  in the middle  , then the nodejs progame could decode the results from iso-8859-1（or other method ） to utf8 and get the chinese  characters to display correctly.

2、could the module support 'cnmarc' ? 

thank you  for you help

**Comment by duolaamenggit** [comment]
well,I have the some question ,would someone help us ,thankyou very much!!

**Comment by adamdickmeiss** [comment]
For ZOOM_record_get, the type parameter is described here:
https://software.indexdata.com/yaz/doc/zoom.records.html

Example: 

Convert a MARC that is encoded in gb2312 to XML in utf-8:

    ZOOM_record_get(rec, "xml;charset=gb2312", &len);

**Comment by DitieNoder** [comment]
> 

Thank you for your guidance.I have two more questions:

1、I donot know how use the command " ZOOM_record_get() " in nodejs .
And  the document says " length is stored in *len.  ",but in the example you says " &len“ , so are these style of writing all workful ?
![image](https://user-images.githubusercontent.com/50827802/170802383-7f4db41f-ef7b-423a-b640-32c57d1e1210.png)
![image](https://user-images.githubusercontent.com/50827802/170802397-c3e2bb00-e2f0-44d7-a7dd-6a05f41c5bb0.png)

2、could the module support 'cnmarc' ?

**Comment by DitieNoder** [comment]
> For `ZOOM_record_get`, the `type` parameter is described here: https://software.indexdata.com/yaz/doc/zoom.records.html
> 
> Example:
> 
> Convert a MARC that is encoded in gb2312 to XML in utf-8:
> 
> ```
> ZOOM_record_get(rec, "xml;charset=gb2312", &len);
> ```
Thank you for your guidance.I have two more questions:

1、I donot know how use the command " ZOOM_record_get() " in nodejs .
And the document says " length is stored in *len. ",but in the example you says " &len“ , so are these style of writing all workful ?
image
image

2、could the module support 'cnmarc' ?

**Comment by adamdickmeiss** [comment]
> > For `ZOOM_record_get`, the `type` parameter is described here: https://software.indexdata.com/yaz/doc/zoom.records.html
> > Example:
> > Convert a MARC that is encoded in gb2312 to XML in utf-8:
> > ```
> > ZOOM_record_get(rec, "xml;charset=gb2312", &len);
> > ```
> 
> Thank you for your guidance.I have two more questions:
> 
> 1、I do not know how to use the command " ZOOM_record_get() " in nodejs .
> 

I don't know either. Perhaps a question like that should be directed elsewhere.

> 2、And the document says " length is stored in *len. ",but in the example you says " &len“ , so are these style of writing all workful ? ![image](https://user-images.githubusercontent.com/50827802/170802511-25db598a-f980-49a7-b341-0a568b1ccd3b.png) ![image](https://user-images.githubusercontent.com/50827802/170802502-56c39ac5-55ac-446c-8b63-01e8f7a3f710.png)

The pointer notation is basic C. I don't know how this is dealt with in the ZOOM node implementation.

> 
> thank you again

**Comment by DitieNoder** [comment]
> > > For `ZOOM_record_get`, the `type` parameter is described here: https://software.indexdata.com/yaz/doc/zoom.records.html
> > > Example:
> > > Convert a MARC that is encoded in gb2312 to XML in utf-8:
> > > ```
> > > ZOOM_record_get(rec, "xml;charset=gb2312", &len);
> > > ```
> > 
> > 
> > Thank you for your guidance.I have two more questions:
> > 1、I do not know how to use the command " ZOOM_record_get() " in nodejs .
> 
> I don't know either. Perhaps a question like that should be directed elsewhere.
> 
> > 2、And the document says " length is stored in *len. ",but in the example you says " &len“ , so are these style of writing all workful ? ![image](https://user-images.githubusercontent.com/50827802/170802511-25db598a-f980-49a7-b341-0a568b1ccd3b.png) ![image](https://user-images.githubusercontent.com/50827802/170802502-56c39ac5-55ac-446c-8b63-01e8f7a3f710.png)
> 
> The pointer notation is basic C. I don't know how this is dealt with in the ZOOM node implementation.
> 
> > thank you again

thank you ,it seem that i should lookup another way somewhere .thank you again for you help, good luck~
