### ISSUE TITLE
yaz-marcdump: fix JSON formatting

### ISSUE THREAD

**Issue by jakub-id** [indexdata/yaz#86]
JSON produced by yaz-marcdump is hardly readable due to the indentation and formatting used. It would be nice if the formatting were similar to what `jq` does. Of course, the output can be piped to `jq` so this is not a high-prio item. 

Alternatively, consider printing out one record-per-line (aka JSON lines format, https://jsonlines.org/). This is nice for processing with command line tools.

**Comment by adamdickmeiss** [comment]
The output that yaz-marcdump uses is very similar to jq; notable exception being that it uses "tab" rather than two spaces. The other being that array starts, makes an extra new line.
